from django.urls import path
from . import views

app_name = "frontend"

urlpatterns = [
    path("image/serve/<str:model_name>/<int:object_id>/<str:field_name>/", views.serve_image, name="serve_image"),
    path("video/stream/<int:video_id>/", views.serve_video, name="serve_video"),
    path("plan/file/<int:archivo_id>/", views.serve_plan_file, name="serve_plan_file"),
    path("biblioteca/pdf/<int:item_id>/", views.serve_biblioteca_pdf, name="serve_biblioteca_pdf"),
    path("", views.login_view, name="login"),
    path("registro/", views.register_view, name="registro"),
    path("home/", views.home, name="home"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("community/", views.community_view, name="community"),
    path("live/", views.live_view, name="live"),
    path("podcast/", views.podcast_view, name="podcast"),
    path("cuestionario/entrenamiento/", views.cuestionario_entrenamiento_view, name="cuestionario_entrenamiento"),
    path("videos/", views.videos_view, name="video"),
    path("recetas/", views.recetas_view, name="recetas"),
    path("bienvenida/", views.bienvenida_view, name="bienvenida"),
    path("cuestionario/alimentacion/", views.cuestionario_alimentacion_view, name="cuestionario_alimentacion"),
    path("panel-admin/", views.panel_admin, name="panel_admin"),
    path("panel-admin/", views.panel_admin, name="panel_admin"),
    path("admin/videos/", views.gestion_videos, name="gestion_videos"),
    path("admin/recetas/", views.gestion_recetas, name="gestion_recetas"),
    #path("admin/videos/eliminar/<int:video_id>/", views.eliminar_video, name="eliminar_video"),
    path('admin/recetas/editar/<int:receta_id>/', views.gestion_recetas_edit, name='editar_receta'),
    path('admin/recetas/eliminar/<int:receta_id>/', views.gestion_recetas_delete, name='eliminar_receta'),
    path("planes/", views.planes_view, name="planes"),
    path("planes/<int:pk>/", views.plan_detalle, name="plan_detalle"),
    path('podcast/', views.podcast_view, name='podcast'),
    path('admin/planes/', views.gestion_planes, name='gestion_planes'),
    path('admin/planes/editar/<int:plan_id>/', views.gestion_planes_edit, name='gestion_planes_edit'),
    path('admin/planes/eliminar/<int:plan_id>/', views.gestion_planes_delete, name='gestion_planes_delete'),    
    path('biblioteca/', views.biblioteca_view, name='biblioteca_view'),
    path('admin/biblioteca/', views.gestion_biblioteca, name='gestion_biblioteca'),
    path('admin/biblioteca/delete/<int:item_id>/', views.gestion_biblioteca_delete, name='gestion_biblioteca_delete'),
    path("admin/podcast/", views.gestion_podcasts, name="gestion_podcasts"),
    path("admin/podcast/delete/<int:item_id>/", views.gestion_podcast_delete, name="gestion_podcast_delete"),
    path('admin/toggle-maintenance/', views.toggle_maintenance_mode, name='toggle_maintenance_mode'),
    path("receta/pdf/<int:receta_id>/", views.serve_receta_pdf, name="serve_receta_pdf"),
    # En frontend/urls.py
    path('podcast/file/<int:archivo_id>/', views.serve_podcast_file, name='serve_podcast_file'),
]
