# Generated by Django 5.2.5 on 2025-10-07 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='recetas/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('objetivo', models.CharField(blank=True, choices=[('resistencia', 'Resistencia'), ('fuerza', 'Fuerza'), ('adiposidad', 'Bajar adiposidad'), ('bienestar', 'Bienestar general')], max_length=50, null=True)),
                ('destacado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('entrenamiento', 'Entrenamiento'), ('nutricion', 'Nutrición'), ('bienestar', 'Bienestar')], default='bienestar', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('destacado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_conditions', models.CharField(blank=True, choices=[('hernia', 'Hernia'), ('escoliosis', 'Escoliosis'), ('rodilla', 'Lesión de rodilla'), ('hombro', 'Lesión de hombro'), ('ninguna', 'Ninguna')], default='ninguna', max_length=50, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('training_goal', models.CharField(blank=True, choices=[('resistencia', 'Resistencia'), ('fuerza', 'Ganar fuerza'), ('adiposidad', 'Bajar adiposidad'), ('bienestar', 'Bienestar general')], max_length=50, null=True)),
                ('training_level', models.CharField(blank=True, choices=[('nunca', 'Nunca entrené'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=50, null=True)),
                ('other_activity', models.CharField(choices=[('no', 'No'), ('correr', 'Correr'), ('natacion', 'Natación'), ('ciclismo', 'Ciclismo'), ('futbol', 'Fútbol'), ('otra', 'Otra')], default='no', max_length=50)),
                ('training_days', models.IntegerField(blank=True, null=True)),
                ('sleep', models.CharField(blank=True, choices=[('7-8', '7/8 horas'), ('dificil', 'Me cuesta descansar')], max_length=50, null=True)),
                ('current_diet', models.CharField(blank=True, choices=[('equilibrada', 'Ordenada y equilibrada'), ('desordenada', 'Desordenada'), ('procesados', 'Muchos ultraprocesados'), ('casera', 'Comida casera'), ('nose', 'No sé qué comer')], max_length=50, null=True)),
                ('diet_restrictions', models.CharField(choices=[('ninguna', 'Ninguna'), ('diabetes', 'Diabetes'), ('celiaquia', 'Celiaquía'), ('veganismo', 'Veganismo'), ('vegetarianismo', 'Vegetarianismo')], default='ninguna', max_length=50)),
                ('thyroid', models.CharField(choices=[('ninguna', 'Ninguna'), ('hiper', 'Hipertiroidismo'), ('hipo', 'Hipotiroidismo')], default='ninguna', max_length=50)),
                ('meals', models.IntegerField(blank=True, null=True)),
                ('snacks', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=10)),
                ('meal_schedule', models.CharField(choices=[('regulares', 'Regulares'), ('irregulares', 'No regulables')], default='regulares', max_length=20)),
                ('hydration', models.CharField(choices=[('poca', 'Consumo poca agua'), ('buena', 'Consumo buena cantidad')], default='poca', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionario_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('destacado', models.BooleanField(default=False)),
                ('objetivo', models.CharField(blank=True, choices=[('resistencia', 'Resistencia'), ('fuerza', 'Fuerza'), ('adiposidad', 'Bajar adiposidad'), ('bienestar', 'Bienestar general')], max_length=50, null=True)),
                ('nivel', models.CharField(blank=True, choices=[('nunca', 'Nunca entrené'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=50, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
