# Generated by Django 5.2.5 on 2025-10-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='training_place',
            field=models.CharField(choices=[('casa', 'En casa'), ('gimnasio', 'En gimnasio'), ('ambos', 'Ambos entornos')], default='casa', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='apto_para',
            field=models.CharField(choices=[('ninguna', 'Sin restricciones'), ('hernia', 'Apto para personas con hernia'), ('rodilla', 'Apto para lesión de rodilla'), ('hombro', 'Apto para lesión de hombro')], default='ninguna', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='entorno',
            field=models.CharField(choices=[('casa', 'En casa'), ('gimnasio', 'En gimnasio'), ('ambos', 'Ambos entornos')], default='ambos', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='requiere_equipo',
            field=models.BooleanField(default=False),
        ),
    ]
