# Generated by Django 5.2.5 on 2025-10-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_questionario_training_place_video_apto_para_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='calorias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Calorías (kcal)'),
        ),
        migrations.AddField(
            model_name='receta',
            name='carboidratos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Carbohidratos (gramos)'),
        ),
        migrations.AddField(
            model_name='receta',
            name='categoria_comida',
            field=models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack'), ('post-entreno', 'Post-entreno')], default='almuerzo', max_length=20, verbose_name='Tipo de Comida'),
        ),
        migrations.AddField(
            model_name='receta',
            name='grasas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Grasas (gramos)'),
        ),
        migrations.AddField(
            model_name='receta',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/portadas/', verbose_name='Imagen de Portada'),
        ),
        migrations.AddField(
            model_name='receta',
            name='porciones',
            field=models.IntegerField(blank=True, null=True, verbose_name='Porciones'),
        ),
        migrations.AddField(
            model_name='receta',
            name='proteinas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Proteínas (gramos)'),
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo_prep',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo de preparación (min)'),
        ),
    ]
