# Generated by Django 5.2.5 on 2025-10-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_receta_calorias_receta_carboidratos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='patologia_tiroides',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('hiper', 'Hipertiroidismo'), ('hipo', 'Hipotiroidismo')], default='ninguna', max_length=50),
        ),
        migrations.AddField(
            model_name='receta',
            name='restriccion_alimentaria',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('diabetes', 'Diabetes'), ('celiaquia', 'Celiaquía'), ('veganismo', 'Veganismo'), ('vegetarianismo', 'Vegetarianismo')], default='ninguna', max_length=50),
        ),
    ]
