# Generated by Django 5.2.5 on 2025-10-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_receta_patologia_tiroides_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='patologia_tiroides',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='restriccion_alimentaria',
        ),
        migrations.AddField(
            model_name='receta',
            name='diet_restrictions',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('diabetes', 'Diabetes'), ('celiaquia', 'Celiaquía'), ('veganismo', 'Veganismo'), ('vegetarianismo', 'Vegetarianismo')], default='ninguna', max_length=50, verbose_name='Restricción Alimentaria'),
        ),
        migrations.AddField(
            model_name='receta',
            name='thyroid',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('hiper', 'Hipertiroidismo'), ('hipo', 'Hipotiroidismo')], default='ninguna', max_length=50, verbose_name='Patología de Tiroides'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='calorias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='carboidratos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='grasas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/portadas/'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='porciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='proteinas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo_prep',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
