# Generated by Django 5.2.5 on 2025-10-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_remove_receta_patologia_tiroides_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='carboidratos',
            new_name='carbohidratos',
        ),
    ]
