# Generated by Django 5.2.5 on 2025-10-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_rename_carboidratos_receta_carbohidratos'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='diet_goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
