# Generated by Django 5.2.5 on 2025-11-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_questionario_diet_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='current_diet',
            field=models.TextField(blank=True, help_text='Describe tu dieta actual', null=True),
        ),
    ]
