# Generated by Django 5.2.5 on 2025-11-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_questionario_current_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='peso_ideal',
            field=models.FloatField(blank=True, help_text='Peso ideal estimado (kg)', null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='training_goal',
            field=models.CharField(blank=True, choices=[('resistencia', 'Resistencia'), ('fuerza', 'Ganar fuerza'), ('adiposidad', 'Bajar adiposidad'), ('bienestar', 'Bienestar general'), ('perder_peso', 'Bajar de peso')], max_length=50, null=True),
        ),
    ]
