# Generated by Django 5.2.5 on 2025-11-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_questionario_peso_ideal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('meses', models.PositiveSmallIntegerField(default=1)),
                ('precio_ars', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('destacado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_individuales', to='frontend.plan'),
        ),
        migrations.CreateModel(
            name='PlanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='plan_docs/%Y/%m/%d/')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='frontend.plan')),
            ],
            options={
                'ordering': ['orden', '-uploaded_at'],
            },
        ),
    ]
