# Generated by Django 5.2.5 on 2025-11-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_plan_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='podcasts/')),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='podcasts/imgs/')),
            ],
        ),
    ]
