# Generated by Django 5.2.5 on 2025-11-20 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_podcast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Plan nutricional', 'verbose_name_plural': 'Planes nutricionales'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='precio_ars',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='spotify_url',
        ),
        migrations.AddField(
            model_name='plan',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='nutrition_plans/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='plan',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='PlanDocument',
        ),
    ]
