# Generated by Django 5.2.5 on 2025-12-02 21:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_alter_plan_options_remove_plan_precio_ars_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='meses',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='plan',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='modificado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='planes_portada/'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlanArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='planes_archivos/%Y/%m/%d/')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='frontend.plan')),
            ],
            options={
                'ordering': ['orden', '-subido_en'],
            },
        ),
    ]
