# Generated by Django 5.2.5 on 2025-12-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_alter_plan_options_remove_plan_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
