# Generated by Django 5.2.5 on 2025-12-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_alter_plan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='plans/content/'),
        ),
        migrations.AddField(
            model_name='plan',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='plans/portadas/'),
        ),
        migrations.AddField(
            model_name='plan',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('recomposicion', 'Recomposición corporal'), ('deficit', 'Descenso de masa adiposa'), ('hipertrofia', 'Aumento de masa muscular'), ('fuerza', 'Ganar fuerza'), ('resistencia', 'Resistencia')], max_length=50, null=True),
        ),
    ]
