# Generated by Django 5.2.5 on 2025-12-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_plan_archivo_plan_imagen_portada_plan_objetivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='archivo',
        ),
    ]
