# Generated by Django 5.2.5 on 2025-12-03 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_remove_plan_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='imagen_portada',
        ),
    ]
