# Generated by Django 5.2.5 on 2025-12-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_remove_plan_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planarchivo',
            name='archivo',
            field=models.FileField(max_length=255, upload_to='planes_archivos/%Y/%m/%d/'),
        ),
    ]
