# Generated by Django 5.2.5 on 2025-12-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_alter_planarchivo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='planarchivo',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
