# Generated by Django 5.2.5 on 2025-12-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_alter_plan_titulo_alter_planarchivo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('resistencia', 'Resistencia'), ('fuerza', 'Fuerza'), ('adiposidad', 'Bajar adiposidad'), ('bienestar', 'Bienestar general'), ('estiramiento', 'Estiramiento')], max_length=50, null=True),
        ),
    ]
