# Generated by Django 5.2.5 on 2025-12-03 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_alter_video_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
