# Generated by Django 5.2.5 on 2025-12-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_podcast_creado_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(upload_to='biblioteca/pdfs/')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='biblioteca/imgs/')),
                ('destacado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
