# Generated by Django 5.2.5 on 2025-12-05 14:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='portada',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
