# Generated by Django 5.2.5 on 2025-12-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_alter_biblioteca_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='categoria_comida',
            field=models.CharField(help_text='Separar por coma si hay más de uno', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='objetivo',
            field=models.CharField(default=' ', help_text='Separar por coma si hay más de uno', max_length=200),
            preserve_default=False,
        ),
    ]
