# Generated by Django 5.2.5 on 2025-12-13 14:00

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_alter_receta_categoria_comida_alter_video_objetivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='archivo_pdf',
        ),
        migrations.CreateModel(
            name='PodcastArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcastarchivos', to='frontend.podcast')),
            ],
        ),
    ]
