# Generated by Django 5.2.5 on 2025-09-14 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=64)),
                ('attempts_left', models.PositiveSmallIntegerField(default=5)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Verificación de email',
                'verbose_name_plural': 'Verificaciones de email',
                'indexes': [models.Index(fields=['email', 'expires_at'], name='email_verif_email_7a9fa4_idx')],
            },
        ),
    ]
