# Generated by Django 5.2.5 on 2025-12-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo_plan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
