# Generated by Django 5.2.5 on 2025-12-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_pago_tipo_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedemail',
            name='vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
