# Generated by Django 5.2.5 on 2025-12-02 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_verifiedemail_vencimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='moneda',
            field=models.CharField(default='ARS', max_length=3),
        ),
        migrations.AddField(
            model_name='pago',
            name='payment_id_externo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='plataforma',
            field=models.CharField(default='mercadopago', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(default='exitoso', max_length=20),
        ),
    ]
