# Generated by Django 5.2.5 on 2026-01-09 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_pago_moneda_pago_payment_id_externo_pago_plataforma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Mensual', 'Plan Mensual'), ('Trimestral', 'Plan Trimestral')], max_length=50, unique=True)),
                ('precio_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_vigencia', models.IntegerField(help_text='Cantidad de días que el usuario tendrá acceso al plan desde la fecha de compra.')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
