# Generated by Django 5.2.5 on 2026-01-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_historialprecioplan_planprecio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialprecioplan',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
