# Generated by Django 5.2.5 on 2026-01-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_historialprecioplan_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='planprecio',
            name='es_descuento',
            field=models.BooleanField(default=False, help_text='¿Este plan tiene un descuento activo?'),
        ),
    ]
